---
- hosts: node1.example.com
  tasks:
  - name: Checking if httpd installed
    yum:
      name: httpd
      state: present
  - name: Checking if httpd is running and enabled
    service:
      name: httpd 
      state: started
      enabled: yes
  - name: Creating a file with content
    copy:
      dest: /var/www/html/index.html
      content: 'Welcome to my web server'
  - name: Looking for installation of firewalld
    yum:
      name: firewalld
      state: present
  - name: Checking if firewalld is running and enabled
    service:
      name: firewalld
      state: started
      enabled: yes
  - name: Opening port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:
    - Restart firewalld
  handlers:
   - name: Restart firewalld
     service:
       name: firewalld
       state: restarted
